services:
    backend:
        build: ./backend
        networks:
         - app-network
        depends_on:
         - database
        ports:
         - "8085:8080"
    database:
        build: ./database
        networks:
         - app-network
        environment:
         POSTGRES_USER: usr
         POSTGRES_PASSWORD: pwd
         POSTGRES_DB: db
        volumes:
          - pgdata:/var/lib/postgresql/data

    httpd:
        build: ./http
        ports:
          - "8086:80"
        networks:
          - app-network
        depends_on:
          - backend

networks:
  app-network:


volumes:
  pgdata:
