- name: Run HTTPD
  docker_container:
    name: http
    image: maxcasado/tp-devops-httpd:latest
    pull: yes
    state: started
    restart_policy: always
    
    networks: 
      - name: app-network
    ports:
      - "80:80"