- name: Run backend
  docker_container:
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    name: app
    image: maxcasado/tp-devops-simple-api:latest
    pull: yes
    restart_policy: always
    state: started
    networks: 
      - name: app-network
