- name: Run database
  docker_container:
    name: database
    state: started
    restart_policy: always
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    image: maxcasado/tp-devops-database:latest
    pull: yes
    networks: 
      - name: app-network